### ISSUE TITLE
Tabular interface widget

### ISSUE THREAD

**Issue by awalter-bnl** [NSLS-II/mily#12]
I am creating an issue here as I am about to start on some multi PR work and wanted a place for people to discuss this as a whole, thereby keeping the PR threads a little cleaner.

### Background
As discussed in a recent NSLS-II/DAMA discussion, a lot of existing spectroscopy (and other) data acquisition programs include a 'tabular interface' whereby users can associate the arguments for a particular 'plan' with a humanly useful 'label'. Each such association is a row in a table, with each column being a particular argument/set of arguments to define the 'plan'. A separate part of the GUI then allows this information to be executed (analogous to being passed to the ``run_engine`` in bluesky). The table is generally not part of the 'queuing system' for plans but rather a place to keep a collection of plan ``arguments`` for re-use/modification later. This is something that has been requested many times by BL staff at NSLS-II, with most currently using 'spreadsheets' to mimic this UI on the floor at present.

To that end I bought up the need for a 'tabular interface widget' to support such an interface as one potential part of the bluesky GUI ecosystem, and after some back and forth at NSLS-II we came up with a plan to implement this. It has also become clear since starting to thin about this that there are _many_ different applications that such a tabular interface could prove useful (see the section below on potential applications).

### Expected implementation Details
Essentially this is describing creating a `tabular interface` widget that works natively with other ``mily`` widgets (both as components of more complex widgets and by using other ``mily`` widgets for editing of cell values). I plan to base this on the built-in ``Qt`` table infrastructure which consists of 4 parts:
1. The 'view' (``PyQt5.QtWidgets.QTableView``) which allows for viewing in a tabular structure and for opening 'editor' widgets for updating the values of each cell.
1. The 'model' (``PyQt5.QtGui.QStandardItemModel``) which stores the data to be displayed in the table.
1. The 'delegate' (``PyQt5.QtWidgets.QStyledItemDelegate``) which performs the interactions between the 'view' and the 'model'. 
1. the 'editors' (``pyQt5.QtWidgets.QtWidget``) that are used to 'edit' the values in the table. These are instantiated by the 'view' when a cell in the table is double-clicked and are used to update the values in that cell.

The delegate has several methods called by either the 'view' or the 'model'  which can be customized within a child class. The ones I think will be important for this work are: 
1.  ``delegate.displayText(value)`` which is called by the 'view' whenever a value is updated in the 'model' and which converts the 'value' from the model into a 'display string'. It returns the string to be displayed in the 'view'.
1.  ``delegate.setEditorData(editor, index)`` which is called by the 'view' whenever it instantiates an 'editor' and needs to extract a 'value' from the 'model' and pass it to the 'editor'.
1.  ``delegate.setModelData(editor, model, index)`` which is called by the 'view' when an 'editior' is closed _and_ a change is made to the value in the cell. It extracts the value from the 'editor' and writes it to the 'model'.
1. ``delegate.createEditor(parent, option, index)`` which is called by the 'view' whenever a cell is double-clicked and returns the instantiated editor to be used for that cell (NOTE: in takes in an 'index' argument which indicates both the row and column for the cell, allowing for different editors to be used for different cells in the table).

The implementation plan is to create child classes of the 'delegate' and the 'view' items that will allow us to use any ``mily`` widget as an 'editor'. Further the 'view' will have some methods added so that it becomes a ``mily`` widget in it's own right.

I also intend to implement a higher level ``mily`` widget that, in addition to the ``mily`` 'view' also contains a series of ``Qt.QWidgets.QPushButtons`` that allow for adding/ deleting/ moving rows in the table. This widget will also be associated with a kwarg only 'function' with each column in the table being mapped to a function kwarg. This function then takes in these 'kwargs' and performs some action. A button that 'executes' this function could also be added.

### Potential Applications
1. A table mapping human readable 'labels' to a, potentially re-usable, set of plan arguments. The 'function' associated with this table would then be essentially a 'plan factory' that takes in the values for each column 'kwarg' and returns a plan, or potentially exports the plan to a ``RunEngine`` queue. This can be thought of as a 'staging' area for plans: where the order of the rows is unimportant, each row should be 'unique', and a row is only removed when  user 'deletes' it. The 'minimally useful version' of such an application is provided as an example in ``blueksy-ui`` in the PR# XXXXXX. A more generalized version that allows users to choose between most of the built-in ``bluesky.plans`` is being worked on but this requires some unique widgets to be developed.
1. A table mapping sample 'labels' to various information about the table, that could be used as a useful interface to an ``amostra`` sample database.
1. As a UI to a ``RunEngine`` queuing system. This is different from 1. above in that in 1. is more of a staging area for plans. In this case the order of the rows would correspond to the 'queue' order (i.e. the plan at the top is the next one to be 'run'), when a plan is shipped to the ``RunEngine`` it is removed from the table (or potentially as an option moved to the last row), multiple versions of the same set of parameters could be included in this table (as the user wants to queue multiple version of the same scan). 
    * I could see 1. and 3. being used together, with the function associated with 1. adding the row to the 'queue' (without removing it from the 'stage' UI). The table in the 'queue' could then have the same columns (and editors) as the 'stage' UI allowing for modifications of queued items (but perhaps not modifying the staged version(s)). 

### Future PR's
- [ ] produce a minimally useful version that takes in a set of kwargs and returns (or executes) a pre-defined plan. --- PR #13  ---
- [ ] produce an example of how the minimally useful version can be used to define 'plans'. --- bluesky-ui PR [#3](https://github.com/bluesky/bluesky-ui/pull/3)---
- [ ]  produce a slightly more generalized version that allows for _most_ of the built-in plans to be selected, as well as _some_ more commonly used args/ kwargs to be defined. --- in progress --- (mostly defining new 'editor' widgets specific to the plans)
- [ ] consider using `tratilets` to allow for easier configuration.
- [ ] consider adding some approach for persisting the table data between sessions.
- [ ] add a 'slot' to the table 'view' and/or 'widget' that emits when a cell has been modified, the exact structure of what the slot emits is yet to be determined.
- [ ] produce an example of how this can be used as a 'queue' interface, perhaps as a partner to the generalized built-in plan 'stage' version indicated above.
- [ ] produce an example of how this might work with the ``amostra`` sample database.
- [ ] ...

**Comment by dmgav** [comment]
The feature is implemented in https://github.com/NSLS-II/mily/pull/14.
